services:
  server:
    build:
      context: .
      target: final
    networks:
      - todo
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:latest
    restart: always
    volumes:
      - "todo-mysql:/var/lib/mysql"
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_HOST: "localhost"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: ${DB_PASSWORD}
    expose:
      - 3306
    networks:
      - todo
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  todo:
    driver: bridge
volumes:
  todo-mysql:
    driver: local
